sudo: required
services:
  - docker

before_install:
  - docker build -t subbs28/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true subbs28/docker-react npm run test -- --coverage
#language: generic 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-353131849081"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY